Repository Juungmini0601/event-nbc, pull requests merged in 2025-05, with the labels that each got.

#3 1/infra/init
  .github/workflows/ci.yml
  .github/workflows/pr-ci.yml
  .springjavaformatconfig
  build.gradle
  gradle.properties
  infrastructure/docker-compose.yml
  infrastructure/grafana/provisioning/dashboards/coupon_dashboard.json
  infrastructure/prometheus/prometheus.yml
  infrastructure/prometheus/rules/.gitkeep
  infrastructure/prometheus/rules/coupon_alert.yml
  settings.gradle
  src/main/java/event/nbc/EventApplication.java
  src/main/resources/application.yml
  src/main/resources/db.yml
  src/main/resources/templates/index.html
  src/test/java/event/nbc/EventApplicationTests.java
  src/test/java/event/nbc/TestEventApplication.java
  src/test/java/event/nbc/TestcontainersConfiguration.java
  src/test/java/me/jungmini/TestCouponApplication.java
Labels: infra

#17 refactor: 락 확장하기 #14
  build.gradle
  src/main/java/event/nbc/aop/DistributedLock.java
  src/main/java/event/nbc/aop/DistributedLockAspect.java
  src/main/java/event/nbc/event/service/EventParticipationService.java
  src/test/java/event/nbc/event/service/EventParticipationServiceTest.java
Labels: ♻️ refactor

#27 fix: 버그 수정 #25
  src/main/java/event/nbc/config/CustomHandshakeHandler.java
  src/main/java/event/nbc/config/WebSocketConfig.java
  src/main/java/event/nbc/event/controller/ClaimController.java
  src/main/java/event/nbc/viewer/handler/WebSocketDisconnectHandler.java
  src/main/resources/templates/gift-page.html
Labels: 🐛 bug
